### ISSUE TITLE
Changing the timer bell Sound

### ISSUE THREAD

**Issue by gokabou** [ukatama/presentation-timer#1]
I think that the sound [【効果音】チーン 一回 高音ver.【仏具：お鈴】](http://commons.nicovideo.jp/material/nc42872) set default is strange.

I changed the timer bell sound to this [呼び出しベル](http://on-jin.com/sound/sei.php?kate=%E9%81%93%E5%85%B7).
How do you think that?

**Comment by esnya** [comment]
It's sound like better.
Could you make a Pull request?

**Comment by gokabou** [comment]
Ok, I try to do.

**Comment by esnya** [comment]
Working on PR #2.
